
r01:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4635
  ttr:
    dist: normal
    params:
      - 5.24
      - 2.97
  setup:
    dist: normal
    params:
      - 0.25
      - 0.09
r02:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 3128
  ttr:
    dist: normal
    params:
      - 5.95
      - 1.94
  setup:
    dist: normal
    params:
      - 0.04
      - 0.05
r03:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 3043
  ttr:
    dist: normal
    params:
      - 5.28
      - 1.91
  setup:
    dist: normal
    params:
      - 0.42
      - 0.17
r04:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 3365
  ttr:
    dist: normal
    params:
      - 2.35
      - 1.16
  setup:
    dist: normal
    params:
      - 0.41
      - 0.22
r05:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4922
  ttr:
    dist: normal
    params:
      - 6.00
      - 2.16
  setup:
    dist: normal
    params:
      - 0.34
      - 0.10
r06:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4089
  ttr:
    dist: normal
    params:
      - 5.14
      - 2.22
  setup:
    dist: normal
    params:
      - 0.49
      - 0.13
r07:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 3200
  ttr:
    dist: normal
    params:
      - 5.31
      - 1.95
  setup:
    dist: normal
    params:
      - 0.16
      - 0.09
r08:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4183
  ttr:
    dist: normal
    params:
      - 4.45
      - 1.93
  setup:
    dist: normal
    params:
      - 0.27
      - 0.21
r09:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4439
  ttr:
    dist: normal
    params:
      - 2.69
      - 1.21
  setup:
    dist: normal
    params:
      - 0.45
      - 0.23
r10:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4558
  ttr:
    dist: normal
    params:
      - 5.01
      - 2.85
  setup:
    dist: normal
    params:
      - 0.49
      - 0.12
r11:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4071
  ttr:
    dist: normal
    params:
      - 3.15
      - 2.39
  setup:
    dist: normal
    params:
      - 0.39
      - 0.17
r12:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 3244
  ttr:
    dist: normal
    params:
      - 5.59
      - 1.5
  setup:
    dist: normal
    params:
      - 0.25
      - 0.05
r13:
  quantity: 1
  tbf:
    dist: expo
    params:
      - 4250
  ttr:
    dist: normal
    params:
      - 2.95
      - 1.71
  setup:
    dist: normal
    params:
      - 0.28
      - 0.07