defaults:
  - _self_
  - products: products
  - resources: resources

# Experiment configuration
experiment:
  number_of_runs: 1
  name: "example"
  # save_folder: "data/experiments"
  save_logs: False
  exp_seed: 123

# Simulation configuration
simulation:
  run_until: 1000
  warmup: 50
  monitor_interval: 500
  monitor_warmup: 0
  delivery_mode: "asReady"
  log_queue: True
  print_mode: "all"
  
hydra:
  run:
    dir: data/experiments/${now:%y%m%d%H%M}_${experiment.name}
  sweep:
    dir: data/experiments
    subdir: ${now:%y%m%d%H%M}_${experiment.name}_${hydra.job.num}

# hydra:
#   run:
#     dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
#   sweep:
#     dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
#     subdir: ${hydra.job.num}